<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="18327" started-at="2025-03-20T08:53:08Z" finished-at="2025-03-20T08:53:26Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="18327" started-at="2025-03-20T08:53:08Z" finished-at="2025-03-20T08:53:26Z">
      <class name="com.mystore.testcases.TC_DataDrivenTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.mystore.testcases.TC_DataDrivenTest@204f30ec]" name="setup" is-config="true" duration-ms="10792" started-at="2025-03-20T08:53:08Z" finished-at="2025-03-20T08:53:19Z">
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="verifyLogin(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.mystore.testcases.TC_DataDrivenTest@204f30ec]" name="verifyLogin" duration-ms="3682" started-at="2025-03-20T08:53:20Z" data-provider="LoginDataProvider" finished-at="2025-03-20T08:53:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[sujata.so@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[$ujata7744]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sujata saund]]>
              </value>
            </param>
          </params>
        </test-method> <!-- verifyLogin -->
        <test-method status="FAIL" signature="verifyLogin(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.mystore.testcases.TC_DataDrivenTest@204f30ec]" name="verifyLogin" duration-ms="2261" started-at="2025-03-20T08:53:24Z" data-provider="LoginDataProvider" finished-at="2025-03-20T08:53:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[sujata.so@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[$ujata7744]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sujata saundale]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<true> but was:<false>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at org.testng.Assert.assertTrue(Assert.java:47)
	at com.mystore.testcases.TC_DataDrivenTest.verifyLogin(TC_DataDrivenTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- verifyLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.mystore.testcases.TC_DataDrivenTest@204f30ec]" name="tearDown" is-config="true" duration-ms="142" started-at="2025-03-20T08:53:26Z" finished-at="2025-03-20T08:53:26Z">
        </test-method> <!-- tearDown -->
      </class> <!-- com.mystore.testcases.TC_DataDrivenTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
